/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package maps;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;

public class App {

    public static void main(String[] args) {
      // hasAttended per person
      ArrayList<Boolean> hasAttended = new ArrayList<>();
      hasAttended.add(true);
      hasAttended.add(false);
      hasAttended.add(true);
      System.out.println(hasAttended);
      int[] arr = {1,2,3};
      System.out.println(arr);
      // Attendance - how do we map? String and ArrayList<Bools> -> Name and an ArrayList<Bools> representing dailyAttendance
      // Attendace - what about a set? String -> Name

      // HASH
      HashMap<String, ArrayList<Boolean>> dailyAttendance = new HashMap<>();
      HashSet<String> classStudents = new HashSet<>();

      classStudents.add("Mat");

      dailyAttendance.put("Alex", hasAttended);

      ArrayList<String> students = new ArrayList<>();
      students.add("Jose");
      students.add("Ben");
      students.add("Mehtab");

      // does Set.add replace the current value?
      if(classStudents.add("Ben")){
        System.out.println("No dupes allowed");
      }

      classStudents.addAll(students);


    }
}
