/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package charmander;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import pokemon.Pokemon;

import java.io.*;
import java.net.HttpURLConnection;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

public class App {
  static Gson gson = new GsonBuilder().setPrettyPrinting().create();

    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws MalformedURLException, IOException {
      HttpURLConnection test = createConnection("https://pokeapi.co/api/v2/poto");
      String stringConnection = readFromConnection(test);
//      Pokemon theMon = convertToPokemon(stringConnection);
//      writeToFile(theMon);
    }
            //METHOD 1 -> urlConnection
  static public HttpURLConnection createConnection(String api) throws MalformedURLException, IOException {
    // 1. Make a URL to the site
    URL pokeURL = new URL(api);
    // openStream()
    // 2. Make a connection to the site with HttpURLConnection
    HttpURLConnection pokeURLConnection = (HttpURLConnection) pokeURL.openConnection();
    // 3. Specify a method
    pokeURLConnection.setRequestMethod("GET");
    return pokeURLConnection;
  }
  // Method 2
  static String readFromConnection(HttpURLConnection connection) throws IOException {
    // Accept URLConnection
    // 4. Read from this connection
    // Stream -> inputStreamReader -> BufferedREader
    InputStreamReader pokeInputStreamReader = new InputStreamReader(connection.getInputStream());
    BufferedReader pokeBufferedReader = new BufferedReader(pokeInputStreamReader);
    String pokeData = pokeBufferedReader.readLine();
    return pokeData;
  }

        // Method 3
  static public Pokemon convertToPokemon(String pokeData){
  // accepts String, inputStream, JSON
    // 5. convert to java Object -> Pokemon
    Pokemon pokemon = gson.fromJson(pokeData, Pokemon.class);
    return pokemon;
  }
        // Method 4
  static public void writeToFile(Pokemon pokemon) throws IOException {
    File pokeFile = new File("./pokemon.json");
    try(FileWriter pokeFileWriter = new FileWriter(pokeFile)){
      gson.toJson(pokemon, pokeFileWriter);
      System.out.println("File was created succesfully");
    } catch (IOException ioe){
      ioe.printStackTrace();
    }
  }
    // 6. Write out to a file

}
