/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package garden;

import garden.plants.*;
import garden.tools.WateringHose;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    @Test void waterSomePlants()
    {
        Plant<Description> cactus = new Cactus<>();
        Description cactusDescription = new Description("I'm a prickly cactus", 1);
        cactus.setDescription(cactusDescription);
        Tomato<String> tomato = new Tomato<>();
        HeirloomTomato<String> heirloomTomato = new HeirloomTomato<>();
        Basil basil = new Basil();
        PassionFlower<String> passionFlower = new PassionFlower<>();
        WateringHose hose = new WateringHose();
        hose.color = "Blue";

        int amountOfCactusWater = 1;

        System.out.println("Hose color before: " + hose.color);

        cactus.water(amountOfCactusWater, hose);
        tomato.water(4, hose);
        heirloomTomato.water(5, hose);
        basil.water(3, hose);
        passionFlower.water(3, hose);

        System.out.println("Hose color before: " + hose.color);

        System.out.println("Cactus water = " + amountOfCactusWater);
        System.out.println("Tomato color = " + tomato.color);
        System.out.println("Cactus description = " + cactus.getDescription());
    }
}
