/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bakery;

import java.util.ArrayList;
import java.util.Arrays;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {

      // Cmd line args
      // ./gradlew run --args "input output transform"
      System.out.println(Arrays.toString(args));

        Bakery zorkBiscuits = new Bakery(true, "Zork's Biscuits");
        Bakery wallyBakery = new Bakery(true, "Wally's Goods");
        Pastry newPastry = new Pastry("Generic pastry");
        newPastry.getName();

        Danish newDanish = new Danish("Danish", true, false, "Banana");
        newPastry.aroma();
//        newDanish.aroma();
        // how do we destroy this object?
//        newDanish = null;
//        newDanish.aroma();

      int[] arr = {1,2,3,4};
      System.out.println(Arrays.toString(arr));
    }

}

