/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package zork;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
  // @ == annotation
    @Test void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library(); //Instantiating an Object
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }

    @Test void reverseArrayReturnsArrayReversed(){
      // Arrange
      int[] testArray = {3,2,1};
      int[] reversedArr = {1,2,3};
      // sut == system under test
      Library sut = new Library(); // Instantiated a new Library Object
      // Act
      int[] result = sut.reverseArray(testArray);
      // Assert
      assertTrue(reversedArr[0] == result[0]);
      // AssertEquals and assertTrue both gave issues when dealing with arrays
      assertArrayEquals(reversedArr, result);
    }
}
