/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package zorkSalon;

import org.junit.jupiter.api.Test;
import zorkSalon.reptile.Chamaleon;

import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }

    @Test void canCreateAChamaleon(){
      //Arrange
      Chamaleon.changeColor(9);
      Chamaleon sut = new Chamaleon(true, (float)0x83E421, true, 4, true);
      sut.changeColor(7);
      Integer legs = sut.getLegs();
      // Act

      //Assert
      assertTrue(sut.getCurrentColor() == (float)0x83E421);
    }

    @Test void animalNoise(){
      //Arrange
//      Animal sut = new Animal();
      Animal.makeNoise();
      Animal.incrementAnimals();
    }


}
