/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package zork;

import java.util.ArrayList;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public int[] reverseArray(int[] arrayOfInts){
      // Type -> var name = instantiate a new integer array with length of input array
      // Java ARRAYS need a length when created
      int[] arrayToReturn = new int[arrayOfInts.length];
      for (int i = 0; i < arrayOfInts.length; i++){
        arrayToReturn[arrayOfInts.length - 1 - i] = arrayOfInts[i];
        // extra logic
      }
      return arrayToReturn;
    }

    public ArrayList<String> reverse(ArrayList<String> arrayToReverse){
      ArrayList<String> newArrList = new ArrayList<>();
      String[] newStrArray = {"Hi", "Zork"};
      return arrayToReverse;
    }
}
