/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cthulu;

import com.google.gson.Gson;

import java.util.ArrayList;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    static Gson gson = new Gson();

    public static void main(String[] args) {
      ArrayList<Worshiper> worshipers = new ArrayList<>();
      Worshiper newPerson = new Worshiper("Jeff");
      worshipers.add(newPerson);
      Cthulu newThulu = new Cthulu(true, 6000, true, true, 8.19f, worshipers,  "HEllo World");
      newThulu.awaken();
      String ThuluSON = gson.toJson(newThulu);
//      ThuluSON.awaken();

      // PRIMITIVE
      String OneToString = gson.toJson(1);
      Integer one = gson.fromJson(OneToString, Integer.class);

      // {"isSleeping":true,"tentacles":6000,"isPresidentialCandidate":true,"isSwimming":true,"numberOfDimensions":8.19,"incantation":"HEllo World"}

      // REading JSON -> Deserialization
      String StringThulu = "{\"isSleeping\":true,\"tentacles\":8000,\"isPresidentialCandidate\":false,\"isSwimming\":false,\"worshipers\":[{\"name\":\"Jeff\"}], \"incantation\":\"HEllo World\"}";

      //{"isSleeping":true,"tentacles":6000,"isPresidentialCandidate":true,"isSwimming":true,"numberOfDimensions":8.19,"worshipers":[{"name":"Jeff"}],"incantation":"HEllo World"}

      Cthulu thobject = gson.fromJson(StringThulu, Cthulu.class);
      thobject.awaken();

    }
}
